### ISSUE TITLE
Errors from users

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/ti-onboarding#41]
### Hestia
https://secure.helpscout.net/conversation/803520600/183709?folderId=212385
```
{  
   "url":"http://gigabitsquad.com/wp-json/ti-sites-lib/v1/import_content?req=Import+Site",
   "ok":false,
   "status":504,
   "statusText":"Gateway Timeout",
   "headers":{  
      "map":{  
         "date":[  
            "Sat, 16 Mar 2019 15:24:30 GMT"
         ],
         "server":[  
            "nginx"
         ],
         "connection":[  
            "keep-alive"
         ],
         "content-length":[  
            "247"
         ],
         "content-type":[  
            "text/html; charset=iso-8859-1"
         ]
      }
   },
   "body":null
}
```

https://secure.helpscout.net/conversation/803352645/183692/
```
{  
   "url":"https://www.ichosproaudio.com/wp-json/ti-sites-lib/v1/import_content?req=Import+Site",
   "ok":false,
   "status":504,
   "statusText":"",
   "headers":{  
      "map":{  
         "pragma":[  
            "no-cache"
         ],
         "date":[  
            "Sat, 16 Mar 2019 08:24:01 GMT"
         ],
         "server":[  
            "cloudflare"
         ],
         "expect-ct":[  
            "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
         ],
         "content-type":[  
            "text/html; charset=UTF-8"
         ],
         "status":[  
            "504"
         ],
         "cache-control":[  
            "no-store, no-cache, must-revalidate, post-check=0, pre-check=0"
         ],
         "cf-ray":[  
            "4b85529849f8cbfa-SIN"
         ],
         "expires":[  
            "Thu, 01 Jan 1970 00:00:01 GMT"
         ]
      }
   },
   "body":null
}
```

https://secure.helpscout.net/conversation/804610781/183826?folderId=212385
```
{ 
"data":"ti__ob_front_page_id_err_1", 
"success":false 
} 
```
https://secure.helpscout.net/conversation/806974996/184096?folderId=212385
```
{
   "url":"https://teefaceim.com/wp-json/ti-sites-lib/v1/import_content?req=Import+Site",
   "ok":false,
   "status":504,
   "statusText":"",
   "headers":{
      "map":{
         "status":[
            "504"
         ],
         "date":[
            "Wed, 20 Mar 2019 22:37:40 GMT"
         ],
         "server":[
            "nginx"
         ],
         "content-length":[
            "247"
         ],
         "content-type":[
            "text/html; charset=iso-8859-1"
         ]
      }
   },
   "body":null
}
```
### Neve
https://secure.helpscout.net/conversation/798660876/183171/
```
{
   "url":"https://www.irg.af/wp-json/ti-sites-lib/v1/initialize_sites_library?req=Init+Sites+Library",
   "ok":false,
   "status":500,
   "statusText":"",
   "headers":{
      "map":{
         "status":[
            "500"
         ],
         "date":[
            "Mon, 11 Mar 2019 10:36:57 GMT"
         ],
         "x-content-type-options":[
            "nosniff"
         ],
         "server":[
            "nginx"
         ],
         "content-length":[
            "660"
         ],
         "x-xss-protection":[
            "1; mode=block"
         ],
         "content-type":[
            "text/html; charset=iso-8859-1"
         ]
      }
   },
   "body":null
}

```
https://secure.helpscout.net/conversation/806624586/184046?folderId=212385
```
{
   "url":"https://echtgut.hippchen.de/wp-json/ti-sites-lib/v1/import_content?req=Import+Site",
   "ok":false,
   "status":504,
   "statusText":"Gateway Time-out",
   "headers":{
      "map":{
         "date":[
            "Wed, 20 Mar 2019 15:30:40 GMT"
         ],
         "server":[
            "nginx"
         ],
         "connection":[
            "keep-alive"
         ],
         "content-length":[
            "578"
         ],
         "content-type":[
            "text/html"
         ]
      }
   },
   "body":null
}
```

**Comment by stefan-cotitosu** [comment]
@abaicus these are all the tickets that I've collected from users yet.

If you need other info from users let me know. For now, I don't know how to handle those situations.

Thanks for looking into this 🙂

**Comment by rodica-andronache** [comment]
@abaicus maybe this can help https://wordpress.org/support/topic/elementor-not-working-with-hestia/ as there seem to be some errors with Elementor

**Comment by abaicus** [comment]
@rodica-andronache seems to be related to this: 

`The gray page can be also due to X frame restrictions and Cross-origin issues. You can see if it is the issue by checking the error messages of your browser console (to do it, click right on your mouse, select "inspect" and then "console". Error messages are written in red). In this case, you will have to change the X-Frame-Options from DENY to SAMEORIGIN. This has to be solved by your hosting company.`
[https://docs.elementor.com/article/184-cant-edit-with-elementor]

**Comment by rodica-andronache** [comment]
thanks, I've suggested that to the user. Thought it might help with other cases as well, but I think this was something different.
Found another one, which I'll leave here for further investigation https://wordpress.org/support/topic/configuration-error-21/

**Comment by abaicus** [comment]
@rodica-andronache @stefan-cotitosu Some big changes are included in the next release for this. These should help fix a lot of the stuff that wasn't working before - https://github.com/Codeinwp/ti-onboarding/pull/52

Also this would help us debug the user sites easier as they'll be provided with a log file they can send us when the import breaks.

**Comment by rodica-andronache** [comment]
@abaicus the new logging mechanism uses some functions not allowed on org. I've tried updating Hestia and I got this:
WARNING: fopen was found in the file parsers.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 518: $fp                = $this->fopen( $file, 'r' );
Line 755: public function fopen( $filename, $mode = 'r' ) {
Line 760: return fopen( $filename, $mode );

WARNING: file_put_contents was found in the file class-themeisle-ob-import-logger.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 178: file_put_contents( $this->log_file_path . $this->log_file_name, $this->get_

WARNING: file_get_contents was found in the file parsers.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 87: $success = $dom->loadXML( file_get_contents( $file ) );
Line 332: if ( ! xml_parse( $xml, file_get_contents( $file ), true ) ) {

WARNING: fclose was found in the file parsers.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 561: $this->fclose( $fp );
Line 779: public function fclose( $fp ) {
Line 784: return fclose( $fp );

REQUIRED: get_option( 'home' ) was found in the file class-themeisle-ob-import-logger.php. Use home_url() instead.
Line 89: $this->log_info( 'Home URL', get_option( 'home' ) );

**Comment by rodica-andronache** [comment]
thanks @abaicus 🥇

**Comment by rodica-andronache** [comment]
@stefan-cotitosu if you have time, could you please try contacting all these people and mention them that we have a new improved version of the theme, and would love to know if they still encounter problems with the import? Thanks 👍

**Comment by stefan-cotitosu** [comment]
@rodica-andronache I have sent them an update, just for the ones on HelpScout.

I will come back with news if they reply.

**Comment by stefan-cotitosu** [comment]
@rodica-andronache Here is a new type of error, I assume that this user has the latest version.
He did not provide site URL or any other details besides the error code:
```
{
"url":"https://www.keyit.no/wp-json/ti-sites-lib/v1/initialize_sites_library",
"ok":false,
"status":0,
"statusText":"",
"headers":{"map":{"":[""]}},
"body":null
} 
```

https://secure.helpscout.net/conversation/843096362/187776?folderId=212385

**Comment by rodica-andronache** [comment]
@stefan-cotitosu not sure there's something we can do there without the parrot, and knowing for sure he's using the latest version, and saw he didn't provide us any of that.

Did you get any answers from those users? Are there any new users with similar problems?

Thanks :)

**Comment by stefan-cotitosu** [comment]
I think we can close this, as the onboarding was enhanced in the meantime and we also have a [troubleshooting guide](https://docs.themeisle.com/article/1157-starter-sites-library-import-is-not-working) for it.
